### PR TITLE
Feat: Opik Integration

### PR DESCRIPTION
**Pull request by jverre**
This PR adds an integration to the [Opik platform](https://github.com/comet-ml/opik), in includes both a new tracer and some documentation updates.

### CODE REVIEW

**Comment by jverre** [comment]
@jjmachan Opik integration is ready for your review

**Comment by shahules786** [comment]
Thanks for the PR @jverre

**Comment by shahules786** [comment]
Hey @jverre Can you fix the CI issue?

**Review by jjmachan — APPROVED** [review]
let me try and fix the CI for you but other wise things look good - thanks a lot for adding the PR :)

**Comment by jjmachan** [comment]
seems like I can't push the changes for some reason - will do that in another PR

**Pull request merged**
