### PR TITLE
modify first prompt of faithfullness

### PR DESCRIPTION
**Pull request by Yongtae723**
This PR is kind of suggestion and related my previous PR #317.
Like previous my PR, if you change fake result into "Final Fantagy is good game" ,which is completely nun sense answer on cell 10 on [this notebook](https://github.com/explodinggradients/ragas/blob/main/docs/howtos/integrations/langchain.ipynb), the result of faithfullness will be 1. This is not good. You can try it out. This is because if the answer is too stupid, first output from LLM generate statement from question.
So I would like to change first PROMPT TEMPLATE that if LLM feel difficult to guess return None.

### CODE REVIEW

**Comment by Yongtae723** [comment]
almost same comment [here](https://github.com/explodinggradients/ragas/pull/317#issuecomment-1820797246), But the point of this PR is  `if the answer is too stupid, LLM guess statement from only question.`, which is not we want.

Thus I recommend to provide the way to LLM if LLM can't guess statement.

But output would be change if prompt change and let me check after your modification of prompt!

**Comment by shahules786** [comment]
@Yongtae723 This has been addressed in #333

**Comment by Yongtae723** [comment]
@shahules786 HI

Thanks you for updating prompt.
But I think the issue of this PR is not fixed.

I understood if the answer is too stupid, the statement will be empty list. But in this case, LLM generate wrong output of the 2nd generation.

You can reproduce by doing following
`if you change fake result into "Final Fantagy is good game" ,which is completely nun sense answer on cell 10 on [this notebook](https://github.com/explodinggradients/ragas/blob/main/docs/howtos/integrations/langchain.ipynb), the result of faithfullness will be 1.`

Do you have any idea to solve this?
my idea is if length of statement is zero, simple additional treatment would be good

**Comment by shahules786** [comment]
@Yongtae723 can you share the full data sample?

**Comment by Yongtae723** [comment]
Yup!

please calculate faithfullness by following data 

```JSON
{'query': 'What is the economic significance of New York City?',
 'ground_truths': ["New York City's economic significance is vast, as it serves as the global financial capital, housing Wall Street and major financial institutions. Its diverse economy spans technology, media, healthcare, education, and more, making it resilient to economic fluctuations. NYC is a hub for international business, attracting global companies, and boasts a large, skilled labor force. Its real estate market, tourism, cultural industries, and educational institutions further fuel its economic prowess. The city's transportation network and global influence amplify its impact on the world stage, solidifying its status as a vital economic player and cultural epicenter."],
 'result': 'Final fantasy is a game.',
 'source_documents': [Document(page_content="New York City's most important economic sector lies in its role as the headquarters for the U.S. financial industry, metonymously known as Wall Street. The city's securities industry continues to form the largest segment of the city's financial sector and is an important economic engine. Many large financial companies are headquartered in New York City, and the city is also home to a burgeoning number of financial startup companies.", metadata={'source': './nyc_wikipedia/nyc_text.txt'}),
  Document(page_content="Significant economic sectors also include non-profit institutions, and universities. Manufacturing declined over the 20th century but still accounts for significant employment. particularly in smaller operations. The city's apparel and garment industry, historically centered on the Garment District in Manhattan, peaked in 1950, when more than 323,000 workers were employed in the industry in New York. In 2015, fewer than 23,000 New York City residents were employed in the manufacture of garments, accessories, and finished textiles, although efforts to revive the industry were underway, and the American fashion industry continues to be metonymized as Seventh Avenue.Chocolate is New York City's leading specialty-food export, with up to $234 million worth of exports each year. Godiva, one of the world's largest chocolatiers, is headquartered in Manhattan, and an unofficial chocolate district in Brooklyn is home to several chocolate makers and retailers. Food processing is a $5 billion", metadata={'source': './nyc_wikipedia/nyc_text.txt'}),
  Document(page_content="New York City is a global hub of business and commerce and an established safe haven for global investors, and is sometimes described as the capital of the world. The term global city was popularized by sociologist Saskia Sassen in her 1991 work, The Global City: New York, London, Tokyo. New York is a center for worldwide banking and finance, health care and life sciences, medical technology and research, retailing, world trade, transportation, tourism, real estate, new media, traditional media, advertising, legal services, accountancy, insurance, both musical and prose theater, fashion, and the arts in the United States; while Silicon Alley, metonymous for New York's broad-spectrum high technology sphere, continues to expand. The Port of New York and New Jersey is a major economic engine, handling a maritime cargo volume in the ten months through October 2022 of over 8.2 million TEUs, benefitting post-Panamax from the expansion of the Panama Canal, and accelerating ahead of", metadata={'source': './nyc_wikipedia/nyc_text.txt'}),
  Document(page_content="California seaports in monthly cargo volumes.Many Fortune 500 corporations are headquartered in New York City, as are a large number of multinational corporations. New York City has been ranked first among cities across the globe in attracting capital, business, and tourists. New York City's role as the top global center for the advertising industry is metonymously reflected as Madison Avenue. The city's fashion industry provides approximately 180,000 employees with $11 billion in annual wages. The non-profit Partnership for New York City, currently headed by Kathryn Wylde, is the city's pre-eminent private business association, comprising approximately 330 corporate leaders in membership. The fashion industry is based in Midtown Manhattan and is represented by the Council of Fashion Designers of America (CDFA), headquartered in Lower Manhattan.", metadata={'source': './nyc_wikipedia/nyc_text.txt'})]}
```

**Comment by Yongtae723** [comment]
BTW, could you reopen this PR please?

**Comment by shahules786** [comment]
You're right, this is due to a minor bug in the code. I am thinking of a way to solve this issue properly. Do you have any suggestions?

**Comment by shahules786** [comment]
@Yongtae723 I have raised #340

**Comment by Yongtae723** [comment]
Close again because #340 solve the problem

**Pull request closed without merging**
