### PR TITLE
chore: remove context_relevancy from library

### PR DESCRIPTION
**Pull request by jjmachan**

### CODE REVIEW

**Review by shahules786 — APPROVED** [review]

**Comment by xiaokening** [comment]
why do you remove context_relevancy from library? can you give me a explanation? thanks!

**Comment by zhiwei2017** [comment]
Hey,
just want to comment on the best practises of semantic versioning, usually people remove functions in at least minor version, not patch version, even though there were deprecation warning for the removed functions. In patch versions, only the bugs should be fixed. Please check the documentation of [semantic versioning](https://semver.org/#spec-item-6)

**Comment by jjmachan** [comment]
@zhiwei2017 that is a good point, thanks for bringing it up. Will keep this in mind moving forward! 🙂 

sorry for the inconvenience

**Comment by mongodben** [comment]
since this has been removed, it'd be great if you could have some other reference-free evaluation metric that looks at how relevant retrieved context is to answer an input. 

Could you also expand on why context relevancy "turned out to be not a useful metric" meriting its removal?

**Comment by jjmachan** [comment]
@shahules786 could you help @mongodben out?

**Comment by shahules786** [comment]
Hi @mongodben thanks for the suggestions.
I just added #1174 to the documentation. We had it for a while but it wasn't displayed in doc making it almost invisible to users. 
Try it out and let us know :)

**Pull request merged**
