### PR TITLE
fix(metrics): avoid getting none in context_recall

### PR DESCRIPTION
**Pull request by yuukidach**
Maybe this isssue https://github.com/explodinggradients/ragas/issues/352 is talking about the same thing.

### CODE REVIEW

**Comment by shahules786** [comment]
Hi @yuukidach , thanks for the PR. This can be treated as a quick fix. IMO doing this might cause incorrect scores, Ideally on such edge cases score should be nan. Would you like to modify it?

**Comment by yuukidach** [comment]
@shahules786 Thanks for reviewing. I‘ve modified the code as required.

**Comment by yuukidach** [comment]
@shahules786 Hi, I just found out that CI failed during type check. These errors should have existed for some time and the CI configurations are not changed. Why did other relevant PRs not trigger this error before? I don't get it.

**Comment by yuukidach** [comment]
> @shahules786 Hi, I just found out that CI failed during type check. These errors should have existed for some time and the CI configurations are not changed. Why did other relevant PRs not trigger this error before? I don't get it.

It seems pyright release a new version yesterday. Fixed to 1.1.338 in `requirements/dev.txt`

**Comment by shahules786** [comment]
Thank you @yuukidach I was wondering the same.

**Comment by jjmachan** [comment]
Hey @yuukidach 
Thank you so much for helping us improve ragas with your PR ❤️ 
Now since it's Christmas and all we wanted to send you a postcard and a couple of stickers as our way of saying thank you for your contribution. If you are interested could you shoot an email at jamesjithin97@gmail.com and I'll tell you more?

Cheers 🙂 
Jithin

**Pull request merged**
