### PR TITLE
Add Generate and Evaluate LlamaIndex compatibility

### PR DESCRIPTION
**Pull request by joaorura**
After upgrading to version 0.2.1 some interfaces I used with llama-index were not present or working correctly. I made some adjustments about this.

### CODE REVIEW

**Comment by jjmachan** [comment]
hey @joaorura thanks for the PR 🙂 

we'll get this merged ASAP

**Comment by jjmachan** [comment]
hey @joaorura I'm made some small tweaks to LlamaIndex docs - I'll also edit the documentation before merging this in

but do take a look at the changes and let me know if you have any doubts 🙂

**Comment by jjmachan** [comment]
hey @joaorura have to close this sadly because there where some changes I can't push into this branch - git issues. So I created a new PR with your commits. I hope its okay

**Comment by joaorura** [comment]
I will take a look at the issues and fix the PR.

**Pull request closed without merging**
