### PR TITLE
Feat: prompt adaptation for test data generation

### PR DESCRIPTION
**Pull request by shahules786**
- [x] prompt adaptation for languages
- [x] Minor bug fixes and assertions
- [x] JSON safe loading

### CODE REVIEW

**Comment by gonznm** [comment]
Hi @shahules786, thank you for your nice work!
Does prompt adaptation also include being able to change the language? As in [metrics](https://docs.ragas.io/en/latest/howtos/applications/use_prompt_adaptation.html)

**Comment by shahules786** [comment]
@gonznm Hey there, Yes. I have been working hard on this feature. It's working now, would love to hear your feedback and  if you have any suggested improvements feel free to raise a PR :)

**Comment by gonznm** [comment]
Awesome! I will def give it a try on monday!

**Review by jjmachan — APPROVED** [review]
we finally have this thanks to @shahules786

**Comment by gonznm** [comment]
Hey there @jjmachan and @shahules786 :)
Adaptation seems to work well in my generation experiments with spanish and OpenAI API! Congrats and thank you!!

Note: I have other issues when trying to use open-source models, but they are not related to adaptation, I'll open an issue for that

**Comment by shahules786** [comment]
Great @gonznm , thanks. Please report the issues so that we can help :)

**Comment by jjmachan** [comment]
thanks a lot for sharing your feedback - really happy to hear its working for you :)

we'll get you sorted on the other issue as well but welcome to the community brother - we are happy to have you here 🙂 ❤️

**Comment by dketterer-enbw** [comment]
I had an issue with adapting a generator to german.

I got an `AssertionError: Adapted output keys do not match with the original output keys` on [this line](https://github.com/explodinggradients/ragas/blob/deded7096486f1b7616e8d11f7e9d6eac731bdd0/src/ragas/llms/prompt.py#L216).

The problem was that one output_key was "verdit" instead of "verdict".

I ended up fixing the typo [https://github.com/explodinggradients/ragas/blob/deded7096486f1b7616e8d11f7e9d6eac731bdd0/src/ragas/testset/prompts.py#L181](here) and now it works!
```
filter_question_prompt = Prompt(
    name="filter_question",
    instruction="""Given a question, classify it based on clarity and specificity. Use only 'Clear' (1) and 'Unclear' (0) as verdict.""",
    examples=[
        {
            "question": "What is the discovery about space?",
            "output": {
                "reason": "The question is too vague and does not specify which discovery about space it is referring to.",
                "verdit": "0",
            },
        },
```

**Pull request merged**
