### PR TITLE
bug fix: embeddings -> embedding

### PR DESCRIPTION
**Pull request by starrywheat**
wrong spelling in embedding

### CODE REVIEW

**Comment by jjmachan** [comment]
Hey @starrywheat there seems to be a conflict here. Could you address that?

also are you there on Discord? would love to chat more there 🙂

**Comment by jjmachan** [comment]
Hey @starrywheat after thinking a bit more about it I think it's better with embeddings because the langchain base class is named embeddings. It's a minor detail but I feel it would avoid a small confusion down the line. 

I'm closing this now but feel free to reopen with your reasons if you still feel that change is needed.

**Comment by starrywheat** [comment]
@jimachan there is still bug unfixed.
The class variable self.embedding  is not consistent in the script. Let's make them all to self.embeddings

**Comment by jjmachan** [comment]
ahh I see, my appologies then. I'm reopening this and we can work off this PR itself.

**Comment by starrywheat** [comment]
@jjmachan Thanks for reopening the PR. 
I created the misspelling in the first place, so I feel like I have  to fix it :) 

And according to your suggestion, I have now use self.embeddings for all the variable name.

**Review by jjmachan — APPROVED** [review]

**Comment by jjmachan** [comment]
Thank you @starrywheat for going through the trouble :)

**Comment by jjmachan** [comment]
Hey @starrywheat 
Thank you so much for helping us improve ragas with your PR ❤️ 
Now since it's Christmas and all we wanted to send you a postcard and a couple of stickers as our way of saying thank you for your contribution. If you are interested could you shoot an email at jamesjithin97@gmail.com and I'll tell you more?

Cheers 🙂 
Jithin

**Pull request merged**
