### PR TITLE
Update README with explanation of Ragas metrics

### PR DESCRIPTION
**Pull request by Yongtae723**
Added to the readme which results each metric is calculated from.

Personally, this information can be found by reading deeper, but for those new to ragas, it will make it easier to get started!

If you think it too much, please just close it!

thanks in advance

### CODE REVIEW

**Comment by jjmachan** [comment]
Thank you so much for taking the time to improve the docs for the other users as well, much appreciated @Yongtae723 ❤️

**Comment by shahules786** [comment]
hi @Yongtae723 , thanks for the PR. I have suggested some changes. Two suggestions here
1. Can you also make similar changes to [metrics.md](https://github.com/explodinggradients/ragas/blob/main/docs/metrics.md)
2. It would be good if you can specify the column names using code formatting. for example, "it is calculated from `answer`"

**Comment by Yongtae723** [comment]
OK I did @shahules786

**Comment by shahules786** [comment]
@Yongtae723 Thanks, I can merge once the comment in answer relevancy part  is addressed.

**Review by shahules786 — APPROVED** [review]

**Comment by Yongtae723** [comment]
@shahules786 Oh!

thank you for fix and update my PR!
also thank you for merging!

**Pull request merged**
