### PR TITLE
Removed the temperature parameter

### PR DESCRIPTION
**Pull request by Kirushikesh**
## **User description**
addressing the issue #656 

This PR removes all the occurrence of temperature keyword in LangChain LLM.

___

## **Description**
- Removed the `temperature` parameter from the `BaseRagasLLM` class methods to align with issue #656.
- Deleted the `get_temperature` method as it is no longer needed.
- Updated tests to reflect the removal of the `temperature` parameter from method signatures.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>base.py</strong><dd><code>Remove temperature parameter from BaseRagasLLM</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/ragas/llms/base.py
<li>Removed the <code>get_temperature</code> method.<br> <li> Removed the <code>temperature</code> parameter from various methods.<br> <li> Simplified the <code>generate</code> and <code>agenerate_text</code> methods by removing <br>temperature handling logic.<br>

</details>
    

  </td>
  <td><a href="https://github.com/explodinggradients/ragas/pull/657/files#diff-f73302c30c4d4472a2acbbb5ee482dea0c869dd519ae2060f92136f36c2a6be0">+0/-17</a>&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>conftest.py</strong><dd><code>Update test mocks to reflect temperature parameter removal</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tests/conftest.py
<li>Updated mock <code>generate_text</code> and <code>agenerate_text</code> methods to remove the <br><code>temperature</code> parameter.<br>

</details>
    

  </td>
  <td><a href="https://github.com/explodinggradients/ragas/pull/657/files#diff-e52e4ddd58b7ef887ab03c04116e676f6280b824ab7469d5d3080e5cba4f2128">+3/-3</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>test_llm.py</strong><dd><code>Update unit tests for temperature parameter removal</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tests/unit/llms/test_llm.py
<li>Updated mock <code>generate_text</code> and <code>agenerate_text</code> methods to remove the <br><code>temperature</code> parameter.<br>

</details>
    

  </td>
  <td><a href="https://github.com/explodinggradients/ragas/pull/657/files#diff-e069ae28490bf61d2825d8febd4bec876bf8e33dcaf505d35e463453cf20fb61">+3/-3</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table><details>
<summary><strong>💡 Usage Guide</strong></summary>

### Checking Your Pull Request
Every time you make a pull request, our system automatically looks through it. We check for security issues, mistakes in how you're setting up your infrastructure, and common code problems. We do this to make sure your changes are solid and won't cause any trouble later.

### Talking to CodeAnt AI
Got a question or need a hand with something in your pull request? You can easily get in touch with CodeAnt AI right here. Just type the following in a comment on your pull request, and replace "Your question here" with whatever you want to ask:
<pre>
<code>/codeantai ask: Your question here</code>
</pre>
This lets you have a chat with CodeAnt AI about your pull request, making it easier to understand and improve your code.

</details>

### CODE REVIEW

**Comment by shahules786** [comment]
Hey @Kirushikesh thanks a lot for the PR bro. As a review, temperate does play a role in some of the ragas metrics like answer-relevancy, that's why we pass it.  But given that some models don't allow this argument to be passed, I would prefer to ignore it for those particular models only rather than doing it for even models that have this capability (for example, OpenAI). 
What do you think?

**Comment by Kirushikesh** [comment]
Hello @shahules786, as far as i gone through the repo only "answer-relevancy" is using the n factor to generate multiple questions, for the rest of metrics in ragas the n is kept as 1 or the default n is 1. Based on my research there is no straight forward solution for this problem, because its not simple to change "temperature" for all LangChain LLM's(like llm.temperature=x). Also, i understood we need 'n' to change the temperature for more dynamic questions in answer-relevancy, but as i mentioned in the issue right, HuggingFace LLM doesn't capture the temperature which you pass in .generate(), it becomes a huge downside of not able to use this metric on Hf LLM.

Another thing, i was wondering how the familiar LangChain and LlamaIndex team, handling this issue of changing temperature of the LLM in runtime, aparantely as far as i understood they are not doing this, one you initialize an LLM with temperature you don't change it, tell me if i am wrong. So the possible work around i see for this problem is,

1. Since only answer-relevancy metric is using this temperature, can we change the prompt to generate all the n questions together like [this](https://python.langchain.com/docs/modules/data_connection/retrievers/MultiQueryRetriever).
2. Ask the user to supply different LLM for the answer relevancy with higher temperature.
3. Use the same LLM to generate n questions without changing any temperature(assuming user initialised the LLM with some non-zero temperature).

Let me know your thoughts. But ig this is something need to be addressed as i was observing Ragas is getting familiar now and even user without OpenAI credentials should get most out of with these metrics.

**Comment by shahules786** [comment]
Hey @Kirushikesh thanks for the reply and the PR. Will consider this, while I also want to explore and think more about the influence of temperature. Will keep you posted.

**Comment by saadbouhya** [comment]
@Kirushikesh did you find a workaround ? otherwise I can't run the evaluation using gemini's model

**Comment by Kirushikesh** [comment]
@saadbouhya no i have done the PR and move to other evaluation library unfortunately ;(

**Comment by Kirushikesh** [comment]
Hello @jjmachan , honestly i was not very keen on getting my PR merged, i was open for other solutions too. But there is no straightforward solution for this problem available yet, so ended up using SelfCheckGPT and Langchain built in evaluators.

**Comment by jjmachan** [comment]
@saadbouhya thanks for suggesting that, you are right that would have been the easiest way to unblock! ❤️ 

btw @Kirushikesh and @saadbouhya we are conducting a roadmap discussion call soon, I would love to invite you guys if you are interested since we would love the feedback. You can see the rough draft #1009 .

if you're interested do share your emails or discord IDs and I'll send over the invite

**Comment by Kirushikesh** [comment]
@jjmachan thanks for inviting, would love to work with you guys and contribute my expertise to the repository. My email: kirushikesh@gmail.com

**Comment by jjmachan** [comment]
just send you one, do vote for the time here too https://rallly.co/invite/WOSpLw4oo9c9 🙂

**Comment by saadbouhya** [comment]
@jjmachan That'd be cool, here's my email: bouhyasaad@gmail.com

**Comment by jjmachan** [comment]
closing this since it is fixed with v0.2, feel free to reopen if still there is something more 🙂

**Pull request closed without merging**
