### PR TITLE
add custom embeddings for answer relevance

### LINKED ISSUE #117: Answer relevancy use custom embedding
At the moment,  this metrics use OpenAIEmbedding by default.
Can we allow this to use custom embedding instead ?

### PR DESCRIPTION
**Pull request by starrywheat**
Fix #117 
@shahules786

### CODE REVIEW

**Comment by shahules786** [comment]
Neat work @starrywheat . As mentioned, I will have to do some ablation analysis on how bge embeddings. Thank you.

**Comment by starrywheat** [comment]
@shahules786  I don't have much experience to ci runners, and I try `make run-ci`  locally but doesn't seem to work. Can you provide some guidance on how to run this ?

**Comment by starrywheat** [comment]
@shahules786  locally run-ci looks good to my changes.
But I do see there are errors in other script (e.g. src/rags/llma_index/evaluation.py) that show error in the run-ci

**Review by shahules786 — APPROVED** [review]

**Comment by shahules786** [comment]
Great work @starrywheat and welcome to the contributors list 🤝

**Pull request merged**
