### PR TITLE
Fix mutable dataclass defaults

### PR DESCRIPTION
**Pull request by yasyf**
Prevents a ValueError on py3.12

### CODE REVIEW

**Comment by yasyf** [comment]
@shahules786 @jjmachan

**Comment by jjmachan** [comment]
thanks a lot @yasyf ❤️

**Comment by shahules786** [comment]
Hey @yasyf Very interesting & curious at the same time to see you were quick to try out experimental test generation ( we haven't made announcement yet) . Would love to chat and learn more about your interest in it https://cal.com/shahul-ragas/30min

**Comment by yasyf** [comment]
@shahules786 still havent got it working actually, hit a few more bugs that I didn't have time to dive into. ya happy to chat!

**Pull request merged**
