### PR TITLE
feat(generator): extend construction to any langchain LLM and Embeddings

### PR DESCRIPTION
**Pull request by mspronesti**
## **User description**
The current version of `with_openai` contains a hardcoded instantiation of `langchain_openai.chat_models.ChatOpenAI`, which makes `TestsetGenerator` very limited and not compatible with completion models, Azure OpenAI models, and open-source models. 

This PR extends `TestsetGenerator` to any `BaseLanguageModel` and `Embeddings` from langchain for versatility, addressing #230, #342, #635, and #636. 

Lastly, I've removed all the occurrences of mutable default arguments (bad antipattern, read [here](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments)).

### CODE REVIEW

**Comment by mspronesti** [comment]
Just finalized the PR - It's ready for review now :)

**Comment by shahules786** [comment]
Wow, thanks man @mspronesti Will review it ASAP

**Comment by mspronesti** [comment]
Hi there @shahules786, any chance this PR gets reviewed? :)

**Comment by shahules786** [comment]
Hi @mspronesti apologies for the late review. @jjmachan was testing this out. Will be reviewed soon.

**Comment by shahules786** [comment]
Hi @mspronesti just finished testing and making some changes to avoid breaking changes. 
I'm not sure if you tested it on any instruct models, but the changes made don't allow the use of instruct models.
Also if you have time can you remove the documentation changes that were made inorder to tackle the breaking change (with_openai)? 

@jjmachan you can do the review now.

**Review by shahules786 — CHANGES_REQUESTED** [review]
remove all changes made to tackle the removal of (with_openai) function

**Comment by mspronesti** [comment]
@shahules786 When I split this PR into two (the second part being #684) I didn't realize that completion models relied on the fact that this [parameter](https://github.com/explodinggradients/ragas/blob/main/src/ragas/llms/base.py#L84) needs to default to `None` not to bump into an `IndexError` (besides the mutable defaults problem).   

Could you try again defaulting that to `None` as done in #684?

Regarding the docs, my suggestion would be to mark `with_openai`  for deprecation (with a decorator) and discontinue it in the next major release. As such, I would advise showcasing the new usage in the docs :)

**Comment by jjmachan** [comment]
hey @mspronesti - I agree from_defaults might be ambiguous so lets keep it as `from_langchain` itself as you first proposed.

as for deprecation I've added the code in this PR but let me think we have to remove it in this version

and for the completion bug - nice catch seems like it fixed the issue ❤️

**Review by jjmachan — APPROVED** [review]

**Comment by mspronesti** [comment]
Hi @jjmachan, thanks for the review :) 

I wouldn't remove `with_openai` in this version, but in the next major release (0.2). I'd decorate it as deprecated now, suggesting `from_lanchain` as alternative. What do you think? :)

**Comment by mspronesti** [comment]
@jjmachan I've just added an extra commit to make the deprecation decorator more versatile and informative, and I've used it on `with_openai` to mark its deprecation as "pending" so that you can schedule that whenever convenient.

**Comment by jjmachan** [comment]
this is awesome @mspronesti - I love the depreciation util func - handy!
Once @shahules786 unblocks us we should be good to go and do a release later today as well


btw would love to hop on a call with you sometime if you are interested @mspronesti 🙂

**Comment by shahules786** [comment]
@mspronesti Yes, that actually makes sense. Let's do that. I'll also add some more docs to help community use non-open ai models with it.

**Review by shahules786 — APPROVED** [review]

**Pull request merged**
