### PR TITLE
 Case-insensitive and whitespace handling for context_precision.

### PR DESCRIPTION
**Pull request by Pauldevillers**
Hello, 

**Title**: Case-insensitive and whitespace handling for response evaluation

**Description** : This PR modifies the response evaluation in the context_precision.py script. The changes include:

- Making the response evaluation case-insensitive: The code now converts each response to lowercase before checking if "yes" is in the response. This ensures that the evaluation is not affected by the case of the response.
- Handling whitespace in responses: The code now strips leading/trailing whitespace from each response before checking if "yes" is in the response. This ensures that the evaluation is not affected by whitespace in the response.

### CODE REVIEW

**Comment by Pauldevillers** [comment]
Seems there is an issue with the 'llama_index.node_parser.simple' package.

**Comment by shahules786** [comment]
Hey @Pauldevillers , No worries. There #291 that will fix the issue.

**Comment by Pauldevillers** [comment]
Nice @shahules786 , can we retriger the checks ?

**Comment by shahules786** [comment]
closing in respect to #289 merged

**Pull request closed without merging**
