### PR TITLE
docs: AI copilot implementation

### PR DESCRIPTION
**Pull request by nickscamara**
Hey team,

We've been thoroughly enjoying Ragas. We stumbled upon you guys after the OpenAI talk and we’ve been super impressed. Here at Mendable, we use RAG pipelines all over so this has been super helpful!

Recently, when trying to implement, we stumbled into some questions. So, we ended up ingesting the Ragas docs into Mendable.ai and started using it to answer some of the questions that we had about the product.

We thought it did an awesome job answering most of them, so we figured to PR and offer it as a feature for your docs. We implemented a small button on the screen's bottom right which unveils an AI-powered chat interface when clicked. There, users can ask questions about Ragas' documentation and even debug code. The bot will learn with the documentation daily so it will be always updated with recent doc changes. (100% free btw)

We would love to hear your feedback! Super excited for what yall are building and hopefully this can help a tiny bit :)

A bit of background: I am one of the co-founders of Mendable.ai. We are supporters of open-source projects and we'd love to offer Mendable for free, with the goal of helping yall out teach developers about your product and answer users queries.

### CODE REVIEW

**Comment by jjmachan** [comment]
hey @nickscamara thanks for putting this PR - we would love to add this in but there are a few problems with how we show search currently and might need a bit of tweaking
so currently it is showing up behind the version tag that RTD puts in like this
image
you can check it out here: https://ragas--294.org.readthedocs.build/en/294/

also ideally we just want one search bar - we don't mind replacing the current search bar if you could implement it with some text based search too like what langchain has
image
but I love the theming of this

Looking forward to working with you to further improve our doc experience for our users. what do you think?

**Comment by nickscamara** [comment]
Hey @jjmachan,

Oh I see, that makes sense!

And yea, we can implement exactly how Langchain does with keyword search as well and replace your current search.

We will make some changes and update the PR here for you to take a look!

Thanks for the feedback. Excited to work with you as well.

**Comment by jjmachan** [comment]
hey @nickscamara let me know if we should do anything from out end - not sure about the internals of configuring mendable but this would be really nice :)

**Comment by nickscamara** [comment]
I believe @rafaelmmiller just submitted some of the changes! @jjmachan Where can I send you the Mendable credentials for you guys to look at the conversations, make changes, and ingest additional data? Thank you!

**Comment by jjmachan** [comment]
wow this is awesome!
just one more issue that I'm seeing which is that the word matching doesn't seem to be working. Ideally mendable should work both as a search and if the users needs it it should be able to ask mendable the question right?
image
you can see the live doc [here](https://ragas--294.org.readthedocs.build/en/294/)

by the way you can send those details to jamesjithin97@gmail.com.

Thanks a lot @nickscamara :)

**Comment by jjmachan** [comment]
hey @nickscamara any updates on this one?

**Comment by nickscamara** [comment]
Hey @jjmachan, so sorry! I missed your last message. We are looking into that issue. And I just sent the login details to your email

Thank you! :)

**Comment by nickscamara** [comment]
Hey @jjmachan it should be fixed! I went ahead and updated it to the newest version as well!

**Comment by jjmachan** [comment]
excited about this the improved experience for docs now :)

**Pull request merged**
