### PR TITLE
fix: bedrock llm error when evaluating rag qa `validate_api_key`

### PR DESCRIPTION
**Pull request by arm-diaz**
Add a conditional statement to check whether `validate_api_key` exists for the ChatModel Object from Langchain #348

### CODE REVIEW

**Comment by arm-diaz** [comment]
This issue should be already resolved with the fix of this PR.

**Review by jjmachan — APPROVED** [review]
thank you so much for the fix @arm-diaz 😄

**Comment by jjmachan** [comment]
Hey @arm-diaz 
Thank you so much for helping us improve ragas with your PR ❤️ 
Now since it's Christmas and all we wanted to send you a postcard and a couple of stickers as our way of saying thank you for your contribution. If you are interested could you shoot an email at jamesjithin97@gmail.com and I'll tell you more?

Cheers 🙂 
Jithin

**Comment by arm-diaz** [comment]
Hey,

Thank you! I will get in touch with that email. Sorry for disappearing the last couple of days/weeks. I was super busy. 

I'll test and review again the framework against bedrock this week. 

Have a great Christmas and holiday season!

**Pull request merged**
