### PR TITLE
fix wrong type annotations and nonexistent types

### PR DESCRIPTION
**Pull request by stydxm**
- The code shown in the document cause warnings in the IDE.  

- `ragas.llms.LangchainLLM` is no longer exists but `from ragas.llms import LangchainLLM` is still left in [document](https://github.com/explodinggradients/ragas/blob/c9ba2be93cb698ff7e691952b6f77378b853ef58/docs/howtos/customisations/gcp-vertexai.ipynb#L128)

First time here, apology for any mistakes.

### CODE REVIEW

**Comment by shahules786** [comment]
Hey @stydxm , thanks for the work.
@jjmachan shouldn't these classes work in ragas without explicitly wrapping LangchainLLMwrapper due to this [line](https://github.com/explodinggradients/ragas/blob/c9ba2be93cb698ff7e691952b6f77378b853ef58/src/ragas/evaluation.py#L148)

**Comment by stydxm** [comment]
> Hey @stydxm , thanks for the work. @jjmachan shouldn't these classes work in ragas without explicitly wrapping LangchainLLMwrapper due to this [line](https://github.com/explodinggradients/ragas/blob/c9ba2be93cb698ff7e691952b6f77378b853ef58/src/ragas/evaluation.py#L148)

Sorry I didn't noticed that. That PR was merged after I found this problem and start working on it yesterday :joy:.  
However the problem in `gcp-vertexai.ipynb` still exists, please allow me minutes to edit it.

**Comment by shahules786** [comment]
@stydxm Thanks buddy :)

**Comment by stydxm** [comment]
> @stydxm Thanks buddy :)

Done

**Review by jjmachan — APPROVED** [review]
wow thank you so much for updating this @stydxm 🙂 
welcome to the contributor list 🎉

**Pull request merged**
