### PR TITLE
fix(spelling): relavancy -> relevancy

### PR DESCRIPTION
**Pull request by mikeldking**
Sorry if this PR is completely not needed but my spell checker corrected this as I was trying it out and I believe you meant "relevancy" for the metrics? Please close if not needed.

### CODE REVIEW

**Comment by shahules786** [comment]
Nice catch @mikeldking

**Comment by jjmachan** [comment]
Hey @mikeldking which service did you run this over with?

**Comment by mikeldking** [comment]
> Hey @mikeldking which service did you run this over with?

Ah prettier probably formatted everything. I can resubmit without the formatting if that's desired. Forgot it formats markdown

**Comment by jjmachan** [comment]
ohh no worries was just curious about what you ran this against to see if this is something I should add in the CI/CD that all

**Comment by jjmachan** [comment]
Hey @mikeldking - long time huh!
Thank you so much for helping us improve ragas with your PR ❤️ 
Now since it's Christmas and all we wanted to send you a postcard and a couple of stickers as our way of saying thank you for your contribution. If you are interested could you shoot an email at jamesjithin97@gmail.com and I'll tell you more?

also, we should catch up some time to learn more about phoenix and what's new

Cheers 🙂 
Jithin

**Comment by mikeldking** [comment]
> Hey @mikeldking - long time huh! Thank you so much for helping us improve ragas with your PR ❤️ Now since it's Christmas and all we wanted to send you a postcard and a couple of stickers as our way of saying thank you for your contribution. If you are interested could you shoot an email at [jamesjithin97@gmail.com](mailto:jamesjithin97@gmail.com) and I'll tell you more?
> 
> also, we should catch up some time to learn more about phoenix and what's new
> 
> Cheers 🙂 Jithin

Hey @jjmachan my pleasure - happy holidays! Yeah Phoenix has even more potential to integrate with Ragas these days. Happy to chat.

**Pull request merged**
