### PR TITLE
feat: translate instruction when adapting prompt

### PR DESCRIPTION
**Pull request by Yunnglin**
When adapting prompts, both the examples and the corresponding instructions are important and need to be translated.

### CODE REVIEW

**Comment by shahules786** [comment]
Hey @Yunnglin Did you observe better results when translating both? We observed pretty good results with only translating a few shot examples. Another reason why we did not translate instruction was that time it introduces ambiguity. FOr example, let's say if the instruction was "Ouptu False if a number greater than zero", this would also translate the word "False", which then causes issues while post-processing.

**Comment by Yunnglin** [comment]
Whether to translate the "instruction" could perhaps be made into an option. When I was generating a Chinese dataset, I found that some "extractor prompts" would lack examples, which led to the generated data not being very effective.

**Comment by shahules786** [comment]
@Yunnglin that suggestion makes sense. Could you make a PR with the same? 
@jjmachan Please share if you have any opinion on this.

**Comment by jjmachan** [comment]
This makes  a ton of sense 

what we can do is take another argument for https://github.com/explodinggradients/ragas/blob/807c313569ba22f69788249c20152a129c21b60b/src/ragas/prompt/pydantic_prompt.py#L217-L223

which converts it 

and it can be controlled through https://github.com/explodinggradients/ragas/blob/807c313569ba22f69788249c20152a129c21b60b/src/ragas/prompt/mixin.py#L55

would be really helpful 🙂

**Comment by Yunnglin** [comment]
*  Add `adapt_instruction: bool=False` parameter.

    Now you can adapt prompt as follows:
    ```python
    import asyncio
    from ragas.metrics import Faithfulness
    from ragas.llms import LangchainLLMWrapper
    
    
    instance = Faithfulness()
    adapted_prompts = asyncio.run(instance.adapt_prompts(language="chinese", llm=LangchainLLMWrapper(chat_model), adapt_instruction=True))
    print(adapted_prompts)

    ```

*  Add `Ensure that the number of output data rows is equal to the number of input data rows.` to the translation prompt since sometimes LLM breaks the single line into multiple lines.

**Review by shahules786 — APPROVED** [review]
LGTM, thanks a lot.

**Pull request merged**
