### PR TITLE
rework classification and recall prompts for mixtral, add json respon…

### PR DESCRIPTION
**Pull request by stepoibm**
Issue #608 

* chg CONTEXT_PRECISION prompt to be more specifc what is expected. Reduces the likelihood of the model generating `verification : {...}` instead of the expected json directly
* chg CONTEXT_RECALL_RA prompt. Reduces likelihood of the model generating int 0 or 1 instead of the expected text "0" or "1".
* chg CONTEXT_RECALL_RA examples to always expect an array instead of switching based on one or multiple statements. Prevents "classification: {...}" vs "classifications: {...}" being generated. Also checks whether "classifications: {...}" was generated as a key and extracts the payload.
* added json payload in log in case of error
* chg expected "Attributed" to "attributed" as the model randomly switches between those

### CODE REVIEW

**Comment by stepoibm** [comment]
Solves #608 for me, but I don't have access to GPT, so I can't validate that users of that model aren't negatively impacted

**Comment by jjmachan** [comment]
thank you so much @stepoibm for fixing this. @shahules786 would help in testing it out and we'll merge this in 🙂 

really sorry for the delay

**Comment by shahules786** [comment]
Hey @stepoibm thanks for the PR. I like the overall changes you have done and think it would be useful for people running mixtral but I doubt if it's generalizable beyond that. I'm thinking of a way in which I can take the generalizable parts from it and include it in ragas. 
In the mean time, our mixtral users could refer to your work :)

**Comment by jjmachan** [comment]
closing this since with v0.2 this has been made much easier

**Pull request closed without merging**
