### PR TITLE
added better styling to reder jupyter notebooks nicely.

### PR DESCRIPTION
**Pull request by zodwick**
especially fixed the spacing issues.
also deleted an unused block in one of the doc pages.

### CODE REVIEW

**Comment by jjmachan** [comment]
great job @zodwick!

just one more thing regarding the code blocks

jupyter
image

md
image


can we make it the same font and size? I think the code block itself is a bit too large (the copy botton is larger too)

**Comment by shahules786** [comment]
I observed that mkdocs [content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#grouping-code-blocks-c_1) used to set different LLMs  does not get rendered in notebook https://github.com/explodinggradients/ragas/pull/1398

**Comment by jjmachan** [comment]
those are not supported in mkdocs-jupyter actually, we will have to render it as html [danielfrg/mkdocs-jupyter: Use Jupyter Notebook in mkdocs](https://github.com/danielfrg/mkdocs-jupyter?tab=readme-ov-file#mkdocs-material-notes)

**Comment by zodwick** [comment]
i made the clipboard icon smaller, but mkdocs-jupyter uses a different svg compared to normal md so there is going to be slight differences
jupyter vs md as of now. close but not exact

image
image

@jjmachan @shahules786

**Review by jjmachan — APPROVED** [review]
this looks great!

**Pull request merged**
